export const styles = {
  mainContainer: {
    flexDirection: 'row',
    width: '90%',
    alignSelf: 'center',
    justifyContent: 'space-around',
    paddingTop: 10,
    height: '90%',
    borderRadius: 12,
  },
  pressable: {
    width: '100%',
    backgroundColor: 'white',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    height: 45,
    marginTop: 10,
  },
  reset: {
    width: '50%',
    backgroundColor: 'white',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    height: 45,
    marginTop: 10,
  },
  checkboxcontainer: {
    width: '50%',
    backgroundColor: 'white',
    marginTop: 10,
    borderRadius: 12,
    marginHorizontal: 8,
  },
};
