import {
  COINS_BALANCE_RECHARGE,
  DEACTIVATE_ACCOUNT,
  LOGOUT,
  MY_PROFILE,
  MY_REQUESTS,
  MY_UPLOADS,
} from './Buttontitles';

export const PROFILEITEMS = [
  MY_PROFILE,
  MY_UPLOADS,
  MY_REQUESTS,
  COINS_BALANCE_RECHARGE,
];
export const ACCOUNTITEMS = [LOGOUT, DEACTIVATE_ACCOUNT];
