export const dummySneakerData = [
  {
    TotalCointsSpentUpon: 0,
    _id: '65c117f60228a5d122e6e5d7',
    Name: 'Nike Airforce 1',
    Brand: 'Nike',
    Photos: [
      'http://localhost:4000/uploads/air-force-1-07-pro-tech-shoes-KHLmTh.webp',
      'http://localhost:4000/uploads/nikeaf1.jpeg',
    ],
    Gender: 'Male',
    Type: 'sell',
    Size: 8,
    Category: 'casual',
    Location: [1.222, 2.33],
    To_Show: true,
    Is_Bought: false,
    Is_Lent: false,
    TransactionComplete: false,
    __v: 0,
  },
  {
    TotalCointsSpentUpon: 0,
    _id: '65c1183f3264c9b5047523fc',
    Name: 'Nike Airforce 1',
    Brand: 'Nike',
    Photos: [
      'http://localhost:4000/uploads/nikeaf1.jpeg',
      'http://localhost:4000/uploads/air-force-1-07-pro-tech-shoes-KHLmTh.webp',
    ],
    Gender: 'Male',
    Type: 'sell',
    Size: 8,
    Category: 'casual',
    Location: [1.222, 2.33],
    To_Show: true,
    Is_Bought: false,
    Is_Lent: false,
    TransactionComplete: false,
    __v: 0,
  },
  {
    TotalCointsSpentUpon: 0,
    _id: '65c11865cc1fe65420fc43fb',
    Name: 'Nike Airforce 1',
    Brand: 'Nike',
    Photos: [
      'http://localhost:4000/uploads/requests/puma.jpeg',
      'http://localhost:4000/uploads/nikeaf1.jpeg',
    ],
    Gender: 'Male',
    Type: 'sell',
    Size: 8,
    Category: 'casual',
    Location: [1.222, 2.33],
    To_Show: true,
    Is_Bought: false,
    Is_Lent: false,
    Owner: '65c114d1362022e90522be96',
    TransactionComplete: false,
    __v: 0,
  },
  {
    TotalCointsSpentUpon: 0,
    _id: '65c11fe25ae7d9d24ef01656',
    Name: 'Nike Airforce 1',
    Brand: 'Nike',
    Photos: [
      'http://localhost:4000/uploads/requests/travis_scott.jpeg',
      'http://localhost:4000/uploads/nikeaf1.jpeg',
    ],
    Gender: 'Male',
    Type: 'sell',
    Size: 8,
    Category: 'casual',
    Location: [1.222, 2.33],
    To_Show: true,
    Is_Bought: false,
    Is_Lent: false,
    Owner: '65c114d1362022e90522be96',
    TransactionComplete: false,
    __v: 0,
  },
  {
    TotalCointsSpentUpon: 0,
    _id: '65c120025ae7d9d24ef0165d',
    Name: 'Nike Airforce 1',
    Brand: 'Nike',
    Photos: [
      'http://localhost:4000/uploads/nikeaf1.jpeg',
      'http://localhost:4000/uploads/nikeaf1.jpeg',
    ],
    Gender: 'Male',
    Type: 'sell',
    Size: 8,
    Category: 'casual',
    Location: [1.222, 2.33],
    To_Show: true,
    Is_Bought: false,
    Is_Lent: false,
    Owner: '65c114d1362022e90522be96',
    TransactionComplete: false,
    __v: 0,
  },
  {
    TotalCointsSpentUpon: 0,
    _id: '65c120c28e6ab6b033b27508',
    Name: 'Nike Airforce 1',
    Brand: 'Nike',
    Photos: [
      'http://localhost:4000/uploads/air-force-1-07-pro-tech-shoes-KHLmTh.webp',
      'http://localhost:4000/uploads/nikeaf1.jpeg',
    ],
    Gender: 'Male',
    Type: 'sell',
    Size: 8,
    Category: 'casual',
    Location: [1.222, 2.33],
    To_Show: true,
    Is_Bought: false,
    Is_Lent: false,
    Owner: '65c114d1362022e90522be96',
    TransactionComplete: false,
    __v: 0,
  },
  {
    TotalCointsSpentUpon: 0,
    _id: '65c1233cedf69913dadefc64',
    Name: 'Nike Airforce 1',
    Brand: 'Nike',
    Photos: [
      'http://localhost:4000/uploads/air-force-1-07-pro-tech-shoes-KHLmTh.webp',
      'http://localhost:4000/uploads/nikeaf1.jpeg',
    ],
    Gender: 'Male',
    Type: 'sell',
    Size: 8,
    Category: 'casual',
    Location: [1.222, 2.33],
    To_Show: true,
    Is_Bought: false,
    Is_Lent: false,
    Owner: '65c114d1362022e90522be96',
    TransactionComplete: false,
    __v: 0,
  },
  {
    TotalCointsSpentUpon: 0,
    _id: '65c3c5451a6ff71dbe76e24a',
    Name: 'Puma fly',
    Brand: 'Puma',
    Photos: [
      'http://localhost:4000/uploads/requests/travis_scott.jpeg',
      'http://localhost:4000/uploads/nikeaf1.jpeg',
    ],
    Gender: 'Male',
    Type: 'sell',
    Size: 8,
    Category: 'casual',
    Location: [1.222, 2.33],
    To_Show: true,
    Is_Bought: false,
    Is_Lent: false,
    Owner: '65c342a1c20c72daac00c9fa',
    TransactionComplete: false,
    __v: 0,
  },
];
